### ISSUE TITLE
Need more words and more clues.

### ISSUE THREAD

**Issue by thepmsquare** [thepmsquare/hangman-game-react#1]
Need more relevant words in clue categories in hangman-game-react/src/AllWords.js

**Comment by Leviter** [comment]
Do you want to keep the categories as is?
And does the category "actors" also include "actresses?

**Comment by thepmsquare** [comment]
i made the categories in a hurry so there are a lot of mistakes, change them as you see fit....
actors was meant to include actresses, i just googled top 5 most popular actors so i guess it didn't return any actresses.

**Comment by Leviter** [comment]
Awesome.... will add a whole lot then.

**Comment by thepmsquare** [comment]
thanks a lot. also i forgot to mention case doesnt matter.

**Comment by Leviter** [comment]
Added a lot of words! And created a PR for it: https://github.com/thepmsquare/hangman-game-react/pull/2

**Comment by Leviter** [comment]
I am not sure how to link the PR to this issue....
